# Generated by Django 5.1.3 on 2024-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='old_cart',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
