# Generated by Django 5.1.3 on 2025-01-22 12:29

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_amout_paid_order_amount_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
